// Sanitized copy of the existing ARMA durable transfer design.
// Source: feature/arma-lawshield-transfer-backend-v2. This file intentionally contains no secrets or production data.
import { defineTable } from "convex/server";
import { v } from "convex/values";
export const lawShieldTransferStatusValidator=v.union(v.literal("DRAFT"),v.literal("PENDING_AUTHORIZATION"),v.literal("AUTHORIZED"),v.literal("READY_TO_SEND"),v.literal("SENT"),v.literal("RECEIPT_VERIFIED"),v.literal("ACCEPTED"),v.literal("REJECTED"),v.literal("QUARANTINED"),v.literal("RECONCILIATION_REQUIRED"));
export const lawShieldTransferTables={
 lawshield_org_mappings:defineTable({armaOrgId:v.id("orgs"),lawShieldOrgId:v.string(),active:v.boolean(),createdByUserId:v.id("users"),createdAt:v.number(),updatedByUserId:v.id("users"),updatedAt:v.number()}).index("by_arma_org",["armaOrgId"]).index("by_lawshield_org",["lawShieldOrgId"]),
 lawshield_case_mappings:defineTable({armaOrgId:v.id("orgs"),incidentId:v.string(),lawShieldOrgId:v.string(),lawShieldCaseId:v.string(),active:v.boolean(),createdByUserId:v.id("users"),createdAt:v.number(),updatedByUserId:v.id("users"),updatedAt:v.number()}).index("by_incident",["armaOrgId","incidentId"]).index("by_lawshield_case",["lawShieldOrgId","lawShieldCaseId"]),
 lawshield_transfer_authorizations:defineTable({transferId:v.string(),armaOrgId:v.id("orgs"),authorizedByUserId:v.id("users"),authorizationReason:v.string(),purposeOfDisclosure:v.optional(v.string()),phiCategories:v.array(v.string()),minimumNecessaryFields:v.array(v.string()),redactedFields:v.array(v.string()),policyDecision:v.union(v.literal("APPROVED"),v.literal("REJECTED")),auditReference:v.optional(v.string()),createdAt:v.number()}).index("by_transfer",["transferId"]).index("by_org_created",["armaOrgId","createdAt"]),
 lawshield_outbound_transfers:defineTable({transferId:v.string(),idempotencyKey:v.string(),armaOrgId:v.id("orgs"),lawShieldOrgId:v.string(),incidentId:v.string(),lawShieldCaseId:v.optional(v.string()),recordType:v.string(),recordId:v.string(),eventSequence:v.number(),payloadHash:v.string(),previousEventHash:v.optional(v.string()),authorizedByUserId:v.optional(v.id("users")),authorizationReason:v.optional(v.string()),status:lawShieldTransferStatusValidator,protocolVersion:v.literal("arma-lawshield.v1"),createdAt:v.number(),approvedAt:v.optional(v.number()),sentAt:v.optional(v.number()),acceptedAt:v.optional(v.number()),rejectedAt:v.optional(v.number()),receiptId:v.optional(v.string()),receiptHash:v.optional(v.string()),lastErrorCode:v.optional(v.string()),retryCount:v.number(),nextRetryAt:v.optional(v.number()),payloadEnvelope:v.object({recordType:v.string(),recordId:v.string(),incidentId:v.string(),lawShieldCaseId:v.optional(v.string()),disclosurePurpose:v.optional(v.string()),data:v.any()}),updatedAt:v.number()}).index("by_transfer_id",["transferId"]).index("by_idempotency",["idempotencyKey"]).index("by_status_created",["status","createdAt"]).index("by_org_incident",["armaOrgId","incidentId"]),
 lawshield_reconciliation:defineTable({transferId:v.string(),expectedPayloadHash:v.string(),lawShieldReceiptId:v.optional(v.string()),receiptHash:v.optional(v.string()),expectedDestination:v.string(),currentArmaState:lawShieldTransferStatusValidator,reportedLawShieldState:v.optional(v.string()),discrepancyCode:v.optional(v.string()),retryCount:v.number(),lastCheckedAt:v.number(),resolutionStatus:v.union(v.literal("OPEN"),v.literal("RESOLVED"),v.literal("QUARANTINED")),authorizedResolverUserId:v.optional(v.id("users")),resolutionNote:v.optional(v.string()),updatedAt:v.number()}).index("by_transfer",["transferId"]).index("by_resolution",["resolutionStatus","updatedAt"]),
 lawshield_transfer_audit:defineTable({transferId:v.optional(v.string()),armaOrgId:v.optional(v.id("orgs")),eventType:v.string(),actorType:v.union(v.literal("HUMAN"),v.literal("SYSTEM"),v.literal("TRANSPORT")),actorUserId:v.optional(v.id("users")),detail:v.optional(v.string()),createdAt:v.number()}).index("by_transfer",["transferId","createdAt"]).index("by_org_created",["armaOrgId","createdAt"])
};
